### ISSUE TITLE
Can't I set divider color in listview?

### ISSUE THREAD

**Issue by cqbqdd11519** [naver/android-pull-to-refresh#1]
in normal listview, i can change divider color by setDivider and setDividerHeight.
But I can't do the same thing in pull-to-refresh listview..

can't i change divider color programmatically?

**Comment by ncoolz** [comment]
You can get an actual list view from `PullToRefreshListView` instance by calling `getRefreshableView()`

```
ListView actualListView = pullToRefreshListView.getRefreshableView();
```

and call divider methods like below, 

```
 actualListView.setDivider(new ColorDrawable(0xff00ff00 /* color */ ));
 actualListView.setDividerHeight(3 /* size */);
```

**Comment by cqbqdd11519** [comment]
한국분이셨구나....ㅋㅋㅋ괜히 영어로.....
해결됐네요 감사합니다!

**Comment by ncoolz** [comment]
아 넵 ㅎㅎ 감사합니다 해결되었다니 다행이네요~
이슈는 닫을게요!

the issue has been solved

**Comment by issacbalaji** [comment]
<ListView
        android:id="@+id/listView1"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" 
        android:divider="#466sdd"
        android:dividerHeight="1px"
        >
    </ListView>
