### ISSUE TITLE
PullToRefreshExpandableListView not applicable with BaseExpandableListAdapter?

### ISSUE THREAD

**Issue by lfdversluis** [naver/android-pull-to-refresh#20]
To me it makes perfect sense to set a BaseExpandableListAdapter as adapter for a PullToRefreshExpandableListView, however this is currently not possible.

Is this a bug? If not how to work around it or what is a better alternative?

**Comment by ncoolz** [comment]
You can get an actual ExpandableListView by calling `getRefrehsableView()` and set an adapter for it. 
See below,

```
ExpandableListView actualListView = mPullRefreshExpandableListView.getRefreshableView();
actualListView.setAdapter(expandableAdapter);
```

**Comment by lfdversluis** [comment]
Ah I see, @ncoolz thanks a lot for your comment. I'll close this issue.
