### ISSUE TITLE
How can i get the same animation when Pulling Up from the bottom in ListView?

### ISSUE THREAD

**Issue by 01joy** [naver/android-pull-to-refresh#23]
Hello everyone, It's a great lib, I have included in my project, I wonder how can i get the same animation when Pulling Up from the bottom in ListView.
1.  I know when pulling up from the bottom, `setOnLastItemVisibleListener` triggered.
2.  So I pasted these code:

``` java
            mListItems.addLast("Added after refresh...");
            mAdapter.notifyDataSetChanged();

            // Call onRefreshComplete when the list has been refreshed.
            mPullRefreshListView.onRefreshComplete();
```

to `onLastItemVisible`.
3.  It did work, but I can't  get the loading animation.
4.  How do i do.

**Comment by 01joy** [comment]
Hey guys, I have figured it out, Just change `OnRefreshListener` to `OnRefreshListener2` in `setOnRefreshListener`, and then override `onPullDownToRefresh` `onPullUpToRefresh` methods.
If you can read Chinese, see [this](http://blog.csdn.net/ueryueryuery/article/details/17440465).

**Comment by ncoolz** [comment]
Cool. Thanks for sharing the solution.
