### ISSUE TITLE
How to trigger pull to refresh and show its loading animation by java code?

### ISSUE THREAD

**Issue by 01joy** [naver/android-pull-to-refresh#25]
I have a fragment using `pull-to-refresh` to refresh my listview, I know when user pull by hand, `OnRefreshListener` triggered, But i want this:

When users open this fragment, they don't have to pull by hand, fragment itself pull to refresh and show loading animation. Please tell me what to do.

Thanks.

**Comment by ncoolz** [comment]
Pull-to-refresh views can refresh programmatically by an API.
Just call `setRefreshing()` as below.

```
mPullRefreshListView.setRefreshing();
```
