### ISSUE TITLE
Unable to use Library in Eclipse

### ISSUE THREAD

**Issue by zeshan-rana7** [naver/android-pull-to-refresh#28]
I'm unable to use this library inside my project in eclipse. Library succefully Import in Eclipse but It give's me lot's of error in library. What is the easiest way to use it?

**Comment by ncoolz** [comment]
This library is a maven project. You have to make your project a maven project by adding a pom.xml like  of [a sample project](https://github.com/naver/android-pull-to-refresh/blob/master/sample/pom.xml). After this, import the library into eclipse, and [reference it](http://developer.android.com/tools/projects/projects-eclipse.html#ReferencingLibraryProject) from your project. This is the easiest way to use it(but, it's not easy either :( . I think that eclipse is too unfit to develop an android app.).

Before doing this, you have to install ADT, m2e, and android connector on eclipse. [This page](http://www.karlmonaghan.com/2013/03/28/eclipse-adt-maven-m2e-android-connector-setup/) may help you for install.

**Comment by ncoolz** [comment]
This issue is closed. If you have any other question, please open new issue.
