### ISSUE TITLE
Customisation option request - don't display labels

### ISSUE THREAD

**Issue by ko0f** [naver/android-pull-to-refresh#29]
I'd like to disable all labels and have just the rotating image in the center.

Couldn't find a way to customize that, settings label strings to an empty string won't help either (image is aligned to the left side).

How can I do this without adding the library as a module to my project?

**Comment by ncoolz** [comment]
There is a solution on #26. Please read my comment on that issue.

**Comment by ko0f** [comment]
Great, thanks.
