### ISSUE TITLE
Please make sure this project is support with  aar

### ISSUE THREAD

**Issue by Zhouxuefei** [naver/android-pull-to-refresh#5]
the version 3.2 in maven repo is type of apklib
please change the packaging type in android-pull-to-refresh / library /pom.xml      &lt;packaging&gt;apklib&lt;/packaging&gt;
to
&lt;packaging&gt;aar&lt;/packaging&gt;
thanks a lot.

**Comment by ncoolz** [comment]
Hello, you can use an aar package in build.gradle as below,

```
dependencies {
    compile 'com.navercorp.pulltorefresh:library:3.2.0@aar'
}
```

Also you can download aar directly in [maven central](http://search.maven.org/remotecontent?filepath=com/navercorp/pulltorefresh/library/3.2.0/library-3.2.0.aar).

It builds both apklib and aar in the setting of pom.xml. This setting is based on actionbarsherlock's.

**Comment by Zhouxuefei** [comment]
actionbarsherlock can use aar, if your maven version is above 3.1.1 and android-maven-plugin is above 3.8.2

**Comment by ncoolz** [comment]
Hi, can you please tell me what the problem is? I don't know why I should change the packaging type in pom.xml. 

The current [pom.xml](https://github.com/nhnopensource/android-pull-to-refresh/blob/master/pom.xml) can make aar and apklib at once on a build. If you wonder about this, see the following code. The code is an additional build step for aar packaging. And it is included in pom.xml.

``` xml
<!-- extracted from actionbarsherlock's pom -->
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>1.2.1</version>
                    <inherited>false</inherited>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>exec</goal>
                            </goals>
                            <configuration>
                                <executable>gradle</executable>
                                <arguments>
                                    <argument>clean</argument>
                                    <argument>assemble</argument>
                                </arguments>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
```

Thank you.

**Comment by Zhouxuefei** [comment]
I think many people want to use the latest version in maven repo,by using 
dependencies {
    compile 'com.navercorp.pulltorefresh:library:+'
}

**Comment by ncoolz** [comment]
Yes. it already supports. The usage is written in my first comment and Quick Start Guide.
If your problem is different from what i understood, please describe it in detail.
Thanks.
