### ISSUE TITLE
How can I customize a loading layout?

### ISSUE THREAD

**Issue by parkjaeiek** [naver/android-pull-to-refresh#9]
문서랑 이것저것 참고해서 해봐는데 잘안되네요...

샘플에도 그러한 예제도없어서 좀 난감하군요

**Comment by ncoolz** [comment]
로딩 레이아웃을 커스터마이징하는 방법은 
[Customization](https://github.com/nhnopensource/android-pull-to-refresh/wiki/Customization)의  "Customizing icon and custom labels ( another way )"를 참고하시면 됩니다.

해당 부분을 여기에 정리하면,
1. LoadingLayout를 오버라이딩하여 커스터마이징한다. 참고로 생성자는 LoadingLayout과 같은 인자를 받는 형태이어야 합니다.
2. assets/pulltorefresh.xml 를 만들고 아래와 같이 커스터마이징한 클래스의 classpath를 집어 넣습니다.

```
    <?xml version="1.0" encoding="UTF-8"?>
    <PullToRefresh>
     <LoadingLayouts>
      <layout name="custom”>com.example.yourproject.CustomLoadingLayout</layout> <!— Add here —>
     </LoadingLayouts>
    </PullToRefresh> 
```
1. PTR 뷰에 ptrAnimationStyle Attribute를 이용하여 커스텀한 것을 적용합니다.

```
<com.handmark.pulltorefresh.library.PullToRefreshListView
    xmlns:ptr="http://schemas.android.com/apk/res-auto"
    android:id="@+id/pull_to_refresh_listview"
    android:layout_height="fill_parent"
    android:layout_width="fill_parent"
    ptr:ptrAnimationStyle="custom"
    /> 
```

이 단계대로 진행하여도 적용이 되지 않는다면, 문제가 있는 샘플 코드를 보내주시면 원인을 찾아보도록 하겠습니다. 

샘플 프로젝트에 예제를 추가하는 것도 좋을 것 같네요. 추후 버젼에 적용해야겠습니다.

---

You can customize a loading layout by referring to  "Customizing icon and custom labels ( another way )" section in [Customization](https://github.com/nhnopensource/android-pull-to-refresh/wiki/Customization) page. The example of the section will be included in future release.

**Comment by ncoolz** [comment]
3.2.2에서 샘플을 추가하였습니다.
The sample of this section is added in 3.2.2 version.
